// @generated drizzle-zero signature:sha256:8faadb07f8dc05873c83fed8e1b7ce9093c114e31e798be70ebf645112785f99
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";

const scenesTable = {
  columns: {
    body: {
      customType: null as unknown as string,
      optional: true,
      type: "string",
    },
    heading: {
      customType: null as unknown as string,
      optional: true,
      type: "string",
    },
    id: {
      customType: null as unknown as string,
      optional: false,
      type: "string",
    },
    ord: {
      customType: null as unknown as number,
      optional: false,
      type: "number",
    },
    scriptId: {
      customType: null as unknown as string,
      optional: false,
      serverName: "script_id",
      type: "string",
    },
    updatedAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: "updated_at",
      type: "number",
    },
  },
  name: "scenes",
  primaryKey: ["id"],
} as const;
const scriptsTable = {
  columns: {
    createdAt: {
      customType: null as unknown as number,
      optional: true,
      serverName: "created_at",
      type: "number",
    },
    id: {
      customType: null as unknown as string,
      optional: false,
      type: "string",
    },
    title: {
      customType: null as unknown as string,
      optional: false,
      type: "string",
    },
  },
  name: "scripts",
  primaryKey: ["id"],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  enableLegacyMutators: true,
  enableLegacyQueries: true,
  relationships: {},
  tables: {
    scenes: scenesTable,
    scripts: scriptsTable,
  },
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "scenes" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Scene = Row<(typeof schema)["tables"]["scenes"]>;
/**
 * Represents a row from the "scripts" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Script = Row<(typeof schema)["tables"]["scripts"]>;

/**
 * Represents the ZQL query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const zql = createBuilder(schema);
/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = zql;

/** Defines the default types for Zero */
declare module "@rocicorp/zero" {
  interface DefaultTypes {
    schema: Schema;
  }
}
